architect:
  - amihaiemil 
env:
  MAVEN_OPTS: "-XX:MaxPermSize=256m -Xmx1g"
merge:
  commanders:
    - amihaiemil 
  script: |-
    mvn clean install -Pcheckstyle
#decrypt:
#  settings.xml: "repo/rcfg/settings.xml.asc"
#  pubring.gpg: "repo/rcfg/pubring.gpg.asc"
#  secring.gpg: "repo/rcfg/secring.gpg.asc"
  
